name = 'goxprint-2'
compatibility_date = '2024-01-01'
compatibility_flags = ['nodejs_compat']

[assets]
directory = "./dist"

[env.production]
name = 'goxprint-2-prod'

[env.development]
name = 'goxprint-2-dev'
